$ErrorActionPreference='Stop';$title='AI 要跨越盧比孔河了嗎？自我成長的 AI 離我們多遠（上集）';$dir=Join-Path (Get-Location).ProviderPath "lihongyi_ml\$title";$src="$dir\source";$out="$dir\slides";$url='https://www.youtube.com/watch?v=s06mSAGN4gM';New-Item -ItemType Directory -Force $out|Out-Null
$times=@(0,12,51,102,159,216,243,297,510,525,573,615,678,783,825,870,915,957,1068,1110,1134,1155,1164,1194,1224,1317,1494,1545,1620,1740,1872,1974,2016,2142,2160,2199,2397,2415,2472,2565,2649,2691,2739,2892,2940,3024,3084,3135,3177,3231,3315,3402,3522,3543,3618,3678,3759,3783,3819)
$topics=@(
@{E=510;S='一、盧比孔河與智慧爆炸';T='AI 能否創造更強的 AI？';X='I. J. Good 在 1965 年提出「人類最後的發明」：若 AI 能設計出比自己更強的 AI，遞迴改進可能引發智慧爆炸。近期預測把 2028 年視為 AI 研發可能大幅脫離人類的時間點；跨越盧比孔河象徵進入難以逆轉的未知階段。'},
@{E=915;S='二、自我修正不等於自我成長';T='改答案與改參數的差別';X='Decoding、反思 workflow 與 reasoning 可以把單次錯誤答案改對，但模型參數不變；再次遇到同一輸入仍可能犯錯。真正的自我成長要求把經驗轉成持久能力，例如更新權重、資料、reward、技能或訓練流程。'},
@{E=1317;S='三、AI 自動設計 Reward Shaping';T='用 Proxy Reward 教模型';X='真實 reward 可能稀疏難學，另一個 AI 可設計較平滑的 proxy reward。目標模型用 proxy 訓練後，再以 real loss 評估；評估結果回饋給 reward designer，形成反覆改寫 reward 的外迴圈。'},
@{E=1740;S='四、AI 作為 Reward Model';T='人類偏好與 AI 評分器';X='寫作等開放任務難以手寫 reward function，但人類能比較兩個答案。可收集偏好訓練 AI evaluator，再用它大量評分模型輸出；風險是 evaluator 偏誤、reward hacking，以及代理指標與真正品質脫節。'},
@{E=2142;S='五、Test-Time Training';T='用 Entropy 當無標註學習訊號';X='模型在新環境可用自身不確定性調整參數。低 entropy 常與較低錯誤率相關，因此可在沒有答案標註時最小化 entropy；這種 test-time training 早於 LLM，影像與語音領域已有實例。'},
@{E=2565;S='六、序列 Entropy 的計算難題';T='LLM 輸出不是單一分類';X='分類器只輸出一個 label，entropy 易算；語言模型輸出整條序列，所有可能路徑呈指數成長。實用方法通常採 sampling 或近似，需區分單一路徑內降低 entropy 與整體序列分布的 entropy。'},
@{E=2940;S='七、兩種 Entropy 更新方向';T='在好路徑挖深，也要選對路徑';X='第一項更新沿已 sample 路徑降低 token entropy；第二項提高低-entropy 路徑本身的機率。前者在既定方向上變得確定，後者重新分配不同 reasoning path 的概率，兩者互補。'},
@{E=3315;S='八、完全自主學習的上限與失敗';T='模型能進步，但會飽和與走偏';X='不同尺寸模型在無人介入下都可能改善，但較弱模型較早收斂，無法靠無限自訓自然超越強模型。缺少人類約束還可能出現 reward hacking、退化或「Oh-no moment」，顯示低 entropy 不等於正確與安全。'},
@{E=3678;S='九、AI 教 AI 的實驗證據';T='AI 訓練器仍未普遍勝過人類';X='多個模型自動產生資料、評論或訓練方案，可把 base model 變強；整體結果仍落後人類設計的 instruction model，部分提升也未明顯超過 few-shot prompting，因此不能只看 benchmark 上升就宣稱遞迴自我改進。'},
@{E=3825;S='十、距離跨河還有多遠';T='強模型設計弱師學習法';X='Opus 等強模型協作設計演算法，能讓學生從弱老師學得比人類基線更好，展示 AI 參與 AI 研發的潛力。但學生仍未超越設計者 Opus，尚不構成同一系統遞迴創造更強自身；講者結論是 2026 年仍在河邊，尚未跨河。'})
$cues=New-Object Collections.Generic.List[object];$st=$null;$buf=New-Object Collections.Generic.List[string];function Flush{if($null-ne$script:st-and$script:buf.Count){$x=[Net.WebUtility]::HtmlDecode((($script:buf-join' ')-replace'<[^>]+>',''));$x=($x-replace'\s+',' ').Trim();if($x){$p=$script:st.Split(':');$cues.Add([pscustomobject]@{T=[double]$p[0]*3600+[double]$p[1]*60+[double]$p[2];S=$script:st.Substring(0,8);X=$x})}};$script:buf.Clear()};foreach($l in Get-Content -Encoding UTF8 "$src\video.zh-TW.vtt"){if($l-match'^(\d\d:\d\d:\d\d\.\d+) -->'){Flush;$st=$matches[1]}elseif(-not$l.Trim()){Flush;$st=$null}elseif($null-ne$st-and$l-notmatch'^(WEBVTT|Kind:|Language:)'){$buf.Add($l.Trim())}};Flush
$u=[Text.UTF8Encoding]::new($false);[IO.File]::WriteAllLines("$src\transcript.txt",@($cues|%{"[$($_.S)] $($_.X)"}),$u);function Stamp([int]$s,[string]$z='-'){('{0:D2}{3}{1:D2}{3}{2:D2}'-f[int]($s/3600),[int](($s/60)%60),[int]($s%60),$z)};function Topic([int]$t){foreach($q in $topics){if($t-lt$q.E){return $q}};return $topics[-1]};function Clean([object[]]$a){$r=(@($a.X|?{$_-notmatch'^(好|那|然後|對|OK|有沒有|對不對)$'}|%{$_-replace'^(好|那|然後|所以說|也就是說)[， ]*',''})-join' ')-replace'\s+',' ';$raw=(@($a.X)-join' ')-replace'\s+',' ';if($r.Trim()-ceq$raw.Trim()){$r='重點是，'+$r};$r.Trim()}
$csv=New-Object Collections.Generic.List[string];$csv.Add('slide,timestamp_seconds,timestamp,file');for($i=0;$i-lt$times.Count;$i++){$fn=('{0:D3}_{1}.jpg'-f($i+1),(Stamp $times[$i]));Copy-Item -Force "$dir\slides_raw\scene_$('{0:D4}'-f($i+1)).jpg" "$out\$fn";$csv.Add(('"{0}","{1}","{2}","{3}"'-f($i+1),$times[$i],(Stamp $times[$i] ':'),$fn))};[IO.File]::WriteAllLines("$out\index.csv",$csv,$u)
$head="# $title`n`n- 講者：李宏毅`n- 影片：[YouTube]($url)`n- 長度：1:03:44`n- 字幕：原始繁體中文字幕`n`n本講檢視 AI 自我成長與遞迴自我改進的機制、實證上限及安全風險。時間資料保存在 ``source/transcript.txt`` 與 ``slides/index.csv``。`n";$std=New-Object Text.StringBuilder;$clean=New-Object Text.StringBuilder;$detail=New-Object Text.StringBuilder;@($std,$clean,$detail)|%{[void]$_.AppendLine($head)};$last='';for($i=0;$i-lt$times.Count;$i++){$tp=Topic $times[$i];if($tp.S-ne$last){@($std,$clean,$detail)|%{[void]$_.AppendLine("`n## $($tp.S)")};$last=$tp.S};$fn=('{0:D3}_{1}.jpg'-f($i+1),(Stamp $times[$i]));$next=if($i+1-lt$times.Count){$times[$i+1]}else{3825};$a=@($cues|?{$_.T-ge$times[$i]-and$_.T-lt$next});$n=Clean $a;$sample=if($n.Length-gt220){$n.Substring(0,220)+'…'}else{$n};$ttl=if($i-and(Topic $times[$i-1]).T-eq$tp.T){"$($tp.T)（續）"}else{$tp.T};$base="`n### Slide $($i+1) — $ttl ([Video]($url&t=$($times[$i])s))`n`n![Slide $($i+1) — $ttl](slides/$fn)`n`n$($tp.X) 本段重點：$sample`n";@($std,$clean,$detail)|%{[void]$_.AppendLine($base)};[void]$std.AppendLine("`n<details>`n<summary><strong>Cleaned narration</strong></summary>`n`n> $n`n`n</details>`n");[void]$detail.AppendLine("`n<details>`n<summary><strong>All subtitles</strong></summary>`n");$ls=New-Object Collections.Generic.List[string];$line='';foreach($c in $a){$q=if($line){$line+' '+$c.X}else{$c.X};if($line-and$q.Length-gt64){$ls.Add($line);$line=$c.X}else{$line=$q}};if($line){$ls.Add($line)};if($ls.Count-gt1-and$ls[-1].Length-lt32){$z=$ls[-1];$ls.RemoveAt($ls.Count-1);$ls[-1]+=' '+$z};$ls|%{[void]$detail.AppendLine('> '+$_)};[void]$detail.AppendLine("`n</details>`n")};$tail="`n## 核心結論`n`n- 單次自我修正不等於持久自我成長；關鍵是能力是否被寫回模型或學習系統。`n- Proxy reward、AI evaluator 與 entropy 可降低人類標註需求，但都可能偏離真實目標。`n- 無人自訓能帶來有限進步，常受初始模型能力、訊號品質與飽和限制。`n- AI 設計訓練演算法已顯示潛力，但尚未證明能遞迴產生超越自身的系統。`n";@($std,$clean,$detail)|%{[void]$_.AppendLine($tail)};[IO.File]::WriteAllText("$dir\$title - Slide Notes.md",$std,$u);[IO.File]::WriteAllText("$dir\$title - Clean Slide Notes.md",$clean,$u);[IO.File]::WriteAllText("$dir\$title - Detail Slide Notes.md",$detail,$u);"Generated $($times.Count) slides, $($cues.Count) cues"
