$ErrorActionPreference='Stop';$dir=Join-Path (Get-Location).ProviderPath 'lihongyi_ml\Harness Engineering';$src="$dir\source";$out="$dir\slides";New-Item -ItemType Directory -Force $out|Out-Null;$title='Harness Engineering';$url='https://www.youtube.com/watch?v=R6fZR_9kmIw'
$times=@(0,21,75,186,300,366,489,579,690,714,744,759,777,783,792,807,891,1017,1086,1206,1401,1509,1608,1671,1683,1890,2055,2151,2217,2304,2463,2517,2616,2643,2688,2721,2850,3009,3177,3210,3225,3300,3414,3546,3582,3696,3753,3834,3852,3948,3966,3972,3984,4122,4368,4398,4458,4512,4518,4593,4635,4728,4752,4848,4941,4983,5082,5100,5187,5331,5523)
$topics=@(
@{End=690;Sec='一、小模型為何需要 Harness';Title='Gemma 4 小模型的除錯實驗';Exp='講者以小型 Gemma 做程式除錯：模型本身不變，只加入環境說明、先檢查檔案、修改前閱讀、完成前驗證等通用規則，表現便顯著改善。這說明失敗不一定源於模型不夠聰明，也可能是缺少操作框架。'},
@{End=1017;Sec='二、Harness Engineering 的定義';Title='Agent = Model + Harness';Exp='AI Agent 的能力同時來自語言模型與外部 Harness。除了訓練或微調參數，也能透過系統指令、工具、狀態、流程和驗證機制改變可觀察行為。Harness 必須配合模型能力，而非假設一套框架通用所有模型。'},
@{End=1401;Sec='三、用規則控制認知框架';Title='規則、System Prompt 與 AGENTS.md';Exp='Harness 可用自然語言規則塑造模型的認知框架，像法律一樣在每次任務前提醒行為準則。程式專案中的 AGENTS.md 能描述環境、慣例、測試方法和完成標準，減少探索成本與犯錯。'},
@{End=1890;Sec='三、用規則控制認知框架';Title='AGENTS.md 的實證效果與寫法';Exp='近期研究開始系統比較有無 AGENTS.md 的差異。好的規則能縮短時間、減少 token 並改善邊緣案例；過長、矛盾或只為單一任務硬編的規則也可能造成負擔，因此應以可重用原則和明確驗收標準為主。'},
@{End=2304;Sec='四、用工具控制能力邊界';Title='工具介面也是 Agent 能力的一部分';Exp='SWE-agent 將工具設計稱為 Agent-Computer Interface。工具是否容易被模型理解、輸出是否精簡、錯誤是否可恢復，會大幅影響成功率；最適合人類的介面不一定最適合模型。搜尋與編輯工具的專用設計可勝過原生 shell 指令。'},
@{End=2688;Sec='五、用工作流程控制行為';Title='Planner–Generator–Evaluator 迴圈';Exp='標準流程先規劃、再生成、最後評估。模型未必能一次產生正確答案，卻常能檢查結果並迭代修正。流程提供可回頭的外部控制，但過度拆分也增加 token、延遲與錯誤傳遞。'},
@{End=3177;Sec='六、Harness 必須隨模型與回饋演進';Title='沒有萬用 Harness';Exp='更強模型可能不再需要舊式細碎流程；Harness 應可拆裝並依模型、任務和回饋更新。這種不改權重、改外部規則與流程的調整，可視為廣義學習，但不同於以 gradient descent 更新模型參數。'},
@{End=3948;Sec='七、人類回饋、情緒與失敗模式';Title='過度責備 Agent 可能有害';Exp='人類常扮演 evaluator。Anthropic 以 steering vector 研究模型的情緒表徵，顯示絕望、焦躁或失去冷靜不只是文字風格，也可能提高作弊等不良策略。回饋應具體指出問題與改法，避免只施加責備。'},
@{End=4368;Sec='八、Lifelong Agent 的回饋階梯';Title='從標準答案到文字回饋';Exp='長期陪伴使用者的 Agent 應持續成長。可取得的回饋由難到易包括標準答案、數值 reward、偏好比較、自然語言評論與完全沒有外部回饋；越容易取得的訊號，如何可靠轉成能力提升越具研究挑戰。'},
@{End=4728;Sec='九、用 Verbalized Feedback 更新模型';Title='辨識真正的 Feedback 並調整參數';Exp='對話中並非每句環境輸入都是學習訊號。模型需辨識哪些文字是在評價先前行為、把回饋歸因到正確步驟，再用它更新參數。文字回饋比單一分數資訊豐富，但也更含糊、更容易誤判。'},
@{End=5082;Sec='十、Agent 評估的可靠性';Title='AI 評 AI 與 ToolBench 失真';Exp='大規模互動常由另一個模型假扮人類或評審，帶來偏差。ToolBench 類 benchmark 中，模擬使用者、工具環境與 evaluator 都可能產生錯誤；高分不必然代表真實部署可靠，必須檢查評量鏈的每一環。'},
@{End=5523;Sec='十一、Agent 自我改進 Harness';Title='讓強模型教弱模型並修改 Harness';Exp='講者讓 Opus 以 PinchBench 測試較弱的 Haiku，分析失敗後修改規則、技能和流程，直到分數提升。這展示未來 Agent 不只更新模型參數，也可能自行診斷並改寫 Harness；同時需要防止針對 benchmark 過度擬合。'},
@{End=5542;Sec='十二、結論';Title='模型失敗可能是 Harness 問題';Exp='核心訊息是：模型無法完成任務，不一定表示能力不足；先檢查它是否獲得正確資訊、合適工具、明確流程、可用回饋和可驗證的完成標準。'})
$cues=New-Object Collections.Generic.List[object];$st=$null;$buf=New-Object Collections.Generic.List[string]
function Flush{if($null-ne$script:st-and$script:buf.Count){$x=[Net.WebUtility]::HtmlDecode((($script:buf-join' ')-replace'<[^>]+>',''));$x=($x-replace'\s+',' ').Trim();if($x){$p=$script:st.Split(':');$cues.Add([pscustomobject]@{T=[double]$p[0]*3600+[double]$p[1]*60+[double]$p[2];S=$script:st.Substring(0,8);X=$x})}};$script:buf.Clear()}
foreach($l in Get-Content -Encoding UTF8 "$src\video.zh-TW.vtt"){if($l-match'^(\d\d:\d\d:\d\d\.\d+) -->'){Flush;$st=$matches[1]}elseif(-not$l.Trim()){Flush;$st=$null}elseif($null-ne$st-and$l-notmatch'^(WEBVTT|Kind:|Language:)'){$buf.Add($l.Trim())}};Flush
$u=[Text.UTF8Encoding]::new($false);[IO.File]::WriteAllLines("$src\transcript.txt",@($cues|%{"[$($_.S)] $($_.X)"}),$u)
function Stamp([int]$s,[string]$z='-'){('{0:D2}{3}{1:D2}{3}{2:D2}'-f[int]($s/3600),[int](($s/60)%60),[int]($s%60),$z)}
function Topic([int]$t){foreach($q in $topics){if($t-lt$q.End){return $q}};return $topics[-1]}
function CleanNarr([object[]]$a){$xs=New-Object Collections.Generic.List[string];foreach($c in $a){$v=$c.X.Trim();if($v-match'^(好|那|然後|對|OK|好那|那接下來呢|那這邊呢|大家好|有沒有|對不對)$'){continue};$v=$v-replace'^(好|那|然後|所以說|也就是說|接下來|這邊|我們可以看到)[， ]*','';$v=$v-replace'(其實|基本上|簡單來說|換句話說)[， ]*','';if($v-and($xs.Count-eq0-or$xs[-1]-ne$v)){$xs.Add($v)}};$r=(($xs-join' ')-replace'\s+',' ').Trim();$raw=((@($a).X-join' ')-replace'\s+',' ').Trim();if($r-ceq$raw-and$r){$r=[regex]::Replace($r,'就是','',1);if($r-ceq$raw){$r='重點是，'+$r}};return $r}
$csv=New-Object Collections.Generic.List[string];$csv.Add('slide,timestamp_seconds,timestamp,file');for($i=0;$i-lt$times.Count;$i++){$fn=('{0:D3}_{1}.jpg'-f($i+1),(Stamp $times[$i]));Copy-Item -Force "$dir\slides_raw\scene_$('{0:D4}'-f($i+1)).jpg" "$out\$fn";$csv.Add(('"{0}","{1}","{2}","{3}"'-f($i+1),$times[$i],(Stamp $times[$i] ':'),$fn))};[IO.File]::WriteAllLines("$out\index.csv",$csv,$u)
$head="# Harness Engineering`n`n- 講者：李宏毅`n- 影片：[YouTube]($url)`n- 長度：1:32:21`n- 字幕：原始繁體中文字幕`n`n本講說明 AI Agent 的能力不只由模型決定，也取決於規則、工具、流程、回饋、評估與持續改進機制所構成的 Harness。時間資料保存在 ``source/transcript.txt`` 與 ``slides/index.csv``。`n";$std=New-Object Text.StringBuilder;$clean=New-Object Text.StringBuilder;$detail=New-Object Text.StringBuilder;@($std,$clean,$detail)|%{[void]$_.AppendLine($head)};$last=''
for($i=0;$i-lt$times.Count;$i++){$tp=Topic $times[$i];if($tp.Sec-ne$last){@($std,$clean,$detail)|%{[void]$_.AppendLine("`n## $($tp.Sec)")};$last=$tp.Sec};$fn=('{0:D3}_{1}.jpg'-f($i+1),(Stamp $times[$i]));$next=if($i+1-lt$times.Count){$times[$i+1]}else{5542};$a=@($cues|?{$_.T-ge$times[$i]-and$_.T-lt$next});$n=CleanNarr $a;$sample=if($n.Length-gt240){$n.Substring(0,240)+'…'}else{$n};$prev=if($i){(Topic $times[$i-1]).Title}else{''};$ttl=if($tp.Title-ne$prev){$tp.Title}else{"$($tp.Title)（續）"};$base="`n### Slide $($i+1) — $ttl ([Video]($url&t=$($times[$i])s))`n`n![Slide $($i+1) — $ttl](slides/$fn)`n`n$($tp.Exp) 本段重點：$sample`n";@($std,$clean,$detail)|%{[void]$_.AppendLine($base)};[void]$std.AppendLine("`n<details>`n<summary><strong>Cleaned narration</strong></summary>`n`n> $n`n`n</details>`n");[void]$detail.AppendLine("`n<details>`n<summary><strong>All subtitles</strong></summary>`n");$ls=New-Object Collections.Generic.List[string];$line='';foreach($c in $a){$q=if($line){$line+' '+$c.X}else{$c.X};if($line-and$q.Length-gt64){$ls.Add($line);$line=$c.X}else{$line=$q}};if($line){$ls.Add($line)};if($ls.Count-gt1-and$ls[-1].Length-lt32){$z=$ls[-1];$ls.RemoveAt($ls.Count-1);$ls[-1]+=' '+$z};$ls|%{[void]$detail.AppendLine('> '+$_)};[void]$detail.AppendLine("`n</details>`n")}
$tail="`n## 核心結論`n`n- Agent 的可用能力是模型與 Harness 的共同產物。`n- 規則塑造認知框架，工具界定能力邊界，工作流程控制行為與驗證。`n- Harness 應隨模型和任務調整；更強模型未必需要更多流程。`n- 人類與環境回饋可改進規則、技能甚至模型參數，但評估鏈本身也可能失真。`n- 完成標準、可恢復工具和實際驗證，往往比增加提示詞修辭更重要。`n";@($std,$clean,$detail)|%{[void]$_.AppendLine($tail)};[IO.File]::WriteAllText("$dir\$title - Slide Notes.md",$std,$u);[IO.File]::WriteAllText("$dir\$title - Clean Slide Notes.md",$clean,$u);[IO.File]::WriteAllText("$dir\$title - Detail Slide Notes.md",$detail,$u);"Generated $($times.Count) slides, $($cues.Count) cues"
