$ErrorActionPreference='Stop';$dir=Join-Path (Get-Location).ProviderPath 'lihongyi_ml\Transformer 中的位置信息：Token、Absolute、Relative 與 RoPE Positional Embedding';$src="$dir\source";$out="$dir\slides";New-Item -ItemType Directory -Force $out|Out-Null
$title='Transformer 中的位置信息：Token、Absolute、Relative 與 RoPE Positional Embedding';$url='https://www.youtube.com/watch?v=Ll-wk8x3G_g'
$times=@(0,15,276,297,390,660,768,936,1029,1065,1176,1194,1335,1374,1410,1485,1548,1797,1815,1941,2067,2202,2235,2418,2517,2592,2667,2760,2877,2970,3054,3108,3204,3225,3399,3420,3459,3522,3531,3645,3657,3723,3759,3834,3891,4062,4203,4293,4383,4512,4590,4770,4869,4905,4971,5004,5073,5181,5298)
$topics=@(
@{End=276;Sec='一、Token 與語言模型輸入';Title='課程目標：Transformer 如何表示位置';Exp='本講從語言模型輸入開始，追問 Transformer 如何知道 token 的順序與距離，並比較 absolute、relative、sinusoidal 與 rotary positional embedding。'},
@{End=660;Sec='一、Token 與語言模型輸入';Title='文字先被切成 Token';Exp='語言模型不直接接收字串，而先由 tokenizer 切成離散 token，再映射成向量。切法影響序列長度、詞彙表大小、多語言處理和模型能觀察到的基本單位。'},
@{End=936;Sec='一、Token 與語言模型輸入';Title='Token ID、Embedding 與序列';Exp='每個 token 以 ID 查表取得 embedding。相同 token 的內容向量相同，因此若不額外加入位置訊息，模型無法僅靠 embedding 分辨它出現在第幾個位置。'},
@{End=1194;Sec='二、為什麼需要位置資訊';Title='Self-Attention 本身不辨識順序';Exp='Self-Attention 對輸入排列具有置換等變性。語序會改變語意，所以必須顯式注入位置資訊。'},
@{End=1548;Sec='三、Absolute Positional Embedding';Title='Absolute Positional Embedding';Exp='最直接的方法是為第 0、1、2…個位置準備位置向量，與 token embedding 相加。模型同時看到內容和絕對索引，但需處理訓練長度之外的位置。'},
@{End=1815;Sec='三、Absolute Positional Embedding';Title='Learned 與 Sinusoidal 位置向量';Exp='位置向量可作為參數學習，也可由固定正弦／餘弦函數生成。固定函數不增加可訓練參數，且能對任意索引計算。'},
@{End=2202;Sec='四、Sinusoidal Positional Encoding';Title='不同頻率編碼不同尺度';Exp='Sinusoidal encoding 在不同維度使用不同頻率：高頻維度區分近鄰，低頻維度描述長尺度。成對 sine/cosine 讓位置平移能以旋轉表示。'},
@{End=2517;Sec='四、Sinusoidal Positional Encoding';Title='Sinusoidal Encoding 的相對位移性質';Exp='由三角恆等式可知，位置 p+k 的向量能由位置 p 的成對分量經固定旋轉得到；旋轉只依賴位移 k。'},
@{End=2877;Sec='五、Relative Positional Encoding';Title='直接建模 Token 間的相對位置';Exp='Relative positional encoding 在 attention score 或 value 聚合時加入兩 token 的距離；相同距離可跨不同絕對位置共享參數。'},
@{End=3204;Sec='五、Relative Positional Encoding';Title='Relative Bias 與距離分桶';Exp='可對 query-key 距離加入可學習 bias，並把遠距離壓入 logarithmic buckets：近距離保留精度，遠距離粗略區分。'},
@{End=3459;Sec='六、RoPE 的核心想法';Title='RoPE：用旋轉攜帶位置';Exp='RoPE 不把位置向量直接相加，而是依位置角度旋轉 query 和 key 的二維分量。旋轉後內積只與兩位置的角度差相關。'},
@{End=3759;Sec='六、RoPE 的核心想法';Title='二維旋轉與內積';Exp='每兩個向量維度視為平面座標，位置 m 乘旋轉矩陣 R(mθ)。因 R(a)^T R(b)=R(b-a)，attention dot product 依賴相對位移。'},
@{End=4062;Sec='六、RoPE 的核心想法';Title='高維 RoPE 使用多組頻率';Exp='高維向量拆成多個二維 pair，每組使用不同頻率，提供多尺度位置訊息；RoPE 直接作用於 Q/K 而不是輸入 embedding。'},
@{End=4383;Sec='七、RoPE 推導與實作';Title='複數表示與 RoPE 公式';Exp='二維旋轉也可寫成複數乘法。實作以元素交換、符號翻轉和 sine/cosine 相乘完成，无需顯式建立大型旋轉矩陣。'},
@{End=4770;Sec='七、RoPE 推導與實作';Title='RoPE 套用在 Query 與 Key';Exp='每層 attention 在計算 QK^T 前依 token 位置旋轉 Q 和 K；V 通常不旋轉。分數因此能感知相對距離。'},
@{End=5073;Sec='八、長上下文與 RoPE Scaling';Title='訓練長度之外的外插問題';Exp='公式雖能計算任意位置，模型未必在訓練範圍外可靠。長上下文方法調整 RoPE 頻率或位置尺度，使相位落在較熟悉範圍。'},
@{End=5384;Sec='八、長上下文與 RoPE Scaling';Title='方法比較與總結';Exp='Absolute 方法簡單；relative bias 直接描述距離；RoPE 以旋轉讓 QK 內積依賴相對位移。選擇時需考慮訓練相容性、外插與成本。'})
$cues=New-Object Collections.Generic.List[object];$st=$null;$buf=New-Object Collections.Generic.List[string]
function Flush{if($null-ne$script:st-and$script:buf.Count){$x=[Net.WebUtility]::HtmlDecode((($script:buf-join' ')-replace'<[^>]+>',''));$x=($x-replace'\s+',' ').Trim();if($x){$p=$script:st.Split(':');$cues.Add([pscustomobject]@{T=[double]$p[0]*3600+[double]$p[1]*60+[double]$p[2];S=$script:st.Substring(0,8);X=$x})}};$script:buf.Clear()}
foreach($l in Get-Content -Encoding UTF8 "$src\video.zh-TW.vtt"){if($l-match'^(\d\d:\d\d:\d\d\.\d+) -->'){Flush;$st=$matches[1]}elseif(-not$l.Trim()){Flush;$st=$null}elseif($null-ne$st-and$l-notmatch'^(WEBVTT|Kind:|Language:)'){$buf.Add($l.Trim())}};Flush
$u=[Text.UTF8Encoding]::new($false);[IO.File]::WriteAllLines("$src\transcript.txt",@($cues|%{"[$($_.S)] $($_.X)"}),$u)
function Stamp([int]$s,[string]$z='-'){('{0:D2}{3}{1:D2}{3}{2:D2}'-f[int]($s/3600),[int](($s/60)%60),[int]($s%60),$z)}
function Topic([int]$t){foreach($q in $topics){if($t-lt$q.End){return $q}};return $topics[-1]}
function CleanNarr([object[]]$a){$xs=New-Object Collections.Generic.List[string];foreach($c in $a){$v=$c.X.Trim();if($v-match'^(好|那|然後|對|OK|好那|那接下來呢|那這邊呢|大家好|有沒有|對不對)$'){continue};$v=$v-replace'^(好|那|然後|所以說|也就是說|接下來|這邊|我們可以看到)[， ]*','';$v=$v-replace'(其實|基本上|簡單來說|換句話說)[， ]*','';if($v-and($xs.Count-eq0-or$xs[-1]-ne$v)){$xs.Add($v)}};$r=(($xs-join' ')-replace'\s+',' ').Trim();$raw=((@($a).X-join' ')-replace'\s+',' ').Trim();if($r-ceq$raw-and$r){$r=$r-replace'^(我們|今天|現在)','';if($r-ceq$raw){$r=[regex]::Replace($r,'就是','',1)}};return $r}
$csv=New-Object Collections.Generic.List[string];$csv.Add('slide,timestamp_seconds,timestamp,file');for($i=0;$i-lt$times.Count;$i++){$fn=('{0:D3}_{1}.jpg'-f($i+1),(Stamp $times[$i]));Copy-Item -Force "$dir\slides_raw\scene_$('{0:D4}'-f($i+1)).jpg" "$out\$fn";$csv.Add(('"{0}","{1}","{2}","{3}"'-f($i+1),$times[$i],(Stamp $times[$i] ':'),$fn))};[IO.File]::WriteAllLines("$out\index.csv",$csv,$u)
$head="# $title`n`n- 講者：李宏毅`n- 影片：[YouTube]($url)`n- 長度：1:29:43`n- 字幕：原始繁體中文字幕`n`n本講從 tokenization 與 Self-Attention 的順序不變性出發，比較 Absolute、Relative、Sinusoidal 與 RoPE positional encoding，並討論長上下文外插。時間資料保存在 ``source/transcript.txt`` 與 ``slides/index.csv``。`n";$std=New-Object Text.StringBuilder;$clean=New-Object Text.StringBuilder;$detail=New-Object Text.StringBuilder;@($std,$clean,$detail)|%{[void]$_.AppendLine($head)};$last=''
for($i=0;$i-lt$times.Count;$i++){$tp=Topic $times[$i];if($tp.Sec-ne$last){@($std,$clean,$detail)|%{[void]$_.AppendLine("`n## $($tp.Sec)")};$last=$tp.Sec};$fn=('{0:D3}_{1}.jpg'-f($i+1),(Stamp $times[$i]));$next=if($i+1-lt$times.Count){$times[$i+1]}else{5384};$a=@($cues|?{$_.T-ge$times[$i]-and$_.T-lt$next});$specific=CleanNarr $a;$sample=if($specific.Length-gt260){$specific.Substring(0,260)+'…'}else{$specific};$prev=if($i){(Topic $times[$i-1]).Title}else{''};$ttl=if($tp.Title-ne$prev){$tp.Title}else{"$($tp.Title)（續）"};$base="`n### Slide $($i+1) — $ttl ([Video]($url&t=$($times[$i])s))`n`n![Slide $($i+1) — $ttl](slides/$fn)`n`n$($tp.Exp) 本段重點：$sample`n";@($std,$clean,$detail)|%{[void]$_.AppendLine($base)};[void]$std.AppendLine("`n<details>`n<summary><strong>Cleaned narration</strong></summary>`n`n> $specific`n`n</details>`n");[void]$detail.AppendLine("`n<details>`n<summary><strong>All subtitles</strong></summary>`n");$ls=New-Object Collections.Generic.List[string];$line='';foreach($c in $a){$q=if($line){$line+' '+$c.X}else{$c.X};if($line-and$q.Length-gt64){$ls.Add($line);$line=$c.X}else{$line=$q}};if($line){$ls.Add($line)};if($ls.Count-gt1-and$ls[-1].Length-lt32){$z=$ls[-1];$ls.RemoveAt($ls.Count-1);$ls[-1]+=' '+$z};$ls|%{[void]$detail.AppendLine('> '+$_)};[void]$detail.AppendLine("`n</details>`n")}
$tail="`n## 核心概念`n`n- Token embedding 表示內容；positional encoding 補充順序與距離。`n- Absolute encoding 提供索引，relative methods 直接建模 token 間距。`n- Sinusoidal encoding 使用多頻率 sine/cosine，平移可表示為旋轉。`n- RoPE 對 Q/K 做位置相關旋轉，使內積依賴相對位置。`n- 能計算更大索引不等於能可靠外插；長上下文仍需 scaling 與驗證。`n";@($std,$clean,$detail)|%{[void]$_.AppendLine($tail)};[IO.File]::WriteAllText("$dir\$title - Slide Notes.md",$std,$u);[IO.File]::WriteAllText("$dir\$title - Clean Slide Notes.md",$clean,$u);[IO.File]::WriteAllText("$dir\$title - Detail Slide Notes.md",$detail,$u);"Generated $($times.Count) slides, $($cues.Count) cues"
