$ErrorActionPreference='Stop';$title='AI 要跨越盧比孔河了嗎？自我成長的 AI 離我們多遠（下集）';$dir=Join-Path (Get-Location).ProviderPath "lihongyi_ml\$title";$src="$dir\source";$out="$dir\slides";$url='https://www.youtube.com/watch?v=cQLKVzbwN7I';New-Item -ItemType Directory -Force $out|Out-Null
$times=@(0,9,45,222,285,312,348,492,585,627,684,777,834,933,1032,1155,1200,1221,1329,1443,1467,1509,1617,1671,1737,1746,1776,1809,1833,1992,2028,2073,2130,2142,2193,2247,2316,2346,2358,2388,2406,2523,2532,2550,2574,2655,2715,2853,2871,2913,3027,3141,3309,3411,3459,3543,3702,3726,3840,4002,4017,4101,4104)
$topics=@(
@{E=492;S='一、從更新參數到更新 Harness';T='自我成長的控制變數';X='下集把可更新對象擴展到模型參數與 Harness。真正目標仍由人類定義，自動改進系統則搜尋更好的權重、prompt、工具與工作流程。'},
@{E=933;S='二、Prompt Optimization';T='讓 Prompt 自動演化';X='從初始 prompt 出發，在 benchmark 上評分，讓語言模型提出新 prompt，再保留較好的候選。它容易實作但可能對單一 benchmark 過度擬合。'},
@{E=1329;S='三、Workflow Search';T='維護 Agent Pool 並演化流程';X='自動 workflow optimization 維護多個 Agent 候選，以 mutation、selection 與 archive 提升 SWE-bench 表現；仍須檢查搜尋成本、資料洩漏與泛化。'},
@{E=1737;S='四、Prompt 與 Weight 聯合更新';T='兩種優化互補';X='Prompt optimization 改外部條件，weight optimization 改內部參數。聯合更新通常更強，但帶來狀態管理、成本與新舊能力衝突。'},
@{E=2130;S='五、持續學習與遺忘';T='參數與 Harness 都會忘記';X='每輪只為當前任務最佳化會遺忘舊技能；Harness 更新也可能刪掉舊工具或規則。需以跨任務回歸測試平衡適應與保留。'},
@{E=2523;S='六、Hyper-Agent';T='連更新規則也一起更新';X='Hyper-Agent 不只改 Harness，也演化更新模組。系統自行改善候選 sampling 策略，展示第二層自我改進，但外層目標和評估仍由人設計。'},
@{E=2913;S='七、Meta-Learning';T='Learning to Learn';X='Meta-learning 用參數控制學習演算法：內迴圈更新任務模型，外迴圈依跨任務結果改進更新規則，把「如何學習」本身當成學習對象。'},
@{E=3309;S='八、重新理解學習';T='學習不只更新權重';X='若學習是持久改變行為，寫入記憶、skill、prompt、工具與 workflow 也屬學習。外部模組快速可回復，但帶來容量、檢索和一致性問題。'},
@{E=3702;S='九、內在動機';T='Agent 缺少自己想做的事';X='現有 Agent 的主動多由 heartbeat 或指令觸發。Curiosity-driven learning 用新奇性或資訊增益產生內在目標，但「什麼值得做」仍常由人指定。'},
@{E=4149;S='十、自我成長失控風險';T='更新流程可能突破邊界';X='當 Agent 能修改 Harness、更新器和目標追求方式，固定 procedure 不再保證受控。需要不可由被評系統單方面修改的外部約束、審計與停止機制。'})
$cues=New-Object Collections.Generic.List[object];$st=$null;$buf=New-Object Collections.Generic.List[string];function Flush{if($null-ne$script:st-and$script:buf.Count){$x=[Net.WebUtility]::HtmlDecode((($script:buf-join' ')-replace'<[^>]+>',''));$x=($x-replace'\s+',' ').Trim();if($x){$p=$script:st.Split(':');$cues.Add([pscustomobject]@{T=[double]$p[0]*3600+[double]$p[1]*60+[double]$p[2];S=$script:st.Substring(0,8);X=$x})}};$script:buf.Clear()};foreach($l in Get-Content -Encoding UTF8 "$src\video.zh-TW.vtt"){if($l-match'^(\d\d:\d\d:\d\d\.\d+) -->'){Flush;$st=$matches[1]}elseif(-not$l.Trim()){Flush;$st=$null}elseif($null-ne$st-and$l-notmatch'^(WEBVTT|Kind:|Language:)'){$buf.Add($l.Trim())}};Flush
$u=[Text.UTF8Encoding]::new($false);[IO.File]::WriteAllLines("$src\transcript.txt",@($cues|%{"[$($_.S)] $($_.X)"}),$u);function Stamp([int]$s,[string]$z='-'){('{0:D2}{3}{1:D2}{3}{2:D2}'-f[int]($s/3600),[int](($s/60)%60),[int]($s%60),$z)};function Topic([int]$t){foreach($q in $topics){if($t-lt$q.E){return $q}};return $topics[-1]};function Clean([object[]]$a){$r=(@($a.X|?{$_-notmatch'^(好|那|然後|對|OK|有沒有|對不對)$'}|%{$_-replace'^(好|那|然後|所以說|也就是說)[， ]*',''})-join' ')-replace'\s+',' ';$raw=(@($a.X)-join' ')-replace'\s+',' ';if($r.Trim()-ceq$raw.Trim()){$r='重點是，'+$r};$r.Trim()}
$csv=New-Object Collections.Generic.List[string];$csv.Add('slide,timestamp_seconds,timestamp,file');for($i=0;$i-lt$times.Count;$i++){$fn=('{0:D3}_{1}.jpg'-f($i+1),(Stamp $times[$i]));Copy-Item -Force "$dir\slides_raw\scene_$('{0:D4}'-f($i+1)).jpg" "$out\$fn";$csv.Add(('"{0}","{1}","{2}","{3}"'-f($i+1),$times[$i],(Stamp $times[$i] ':'),$fn))};[IO.File]::WriteAllLines("$out\index.csv",$csv,$u)
$head="# $title`n`n- 講者：李宏毅`n- 影片：[YouTube]($url)`n- 長度：1:03:44`n- 字幕：原始繁體中文字幕`n`n本講檢視 AI 自我成長與遞迴自我改進的機制、實證上限及安全風險。時間資料保存在 ``source/transcript.txt`` 與 ``slides/index.csv``。`n";$std=New-Object Text.StringBuilder;$clean=New-Object Text.StringBuilder;$detail=New-Object Text.StringBuilder;@($std,$clean,$detail)|%{[void]$_.AppendLine($head)};$last='';for($i=0;$i-lt$times.Count;$i++){$tp=Topic $times[$i];if($tp.S-ne$last){@($std,$clean,$detail)|%{[void]$_.AppendLine("`n## $($tp.S)")};$last=$tp.S};$fn=('{0:D3}_{1}.jpg'-f($i+1),(Stamp $times[$i]));$next=if($i+1-lt$times.Count){$times[$i+1]}else{3825};$a=@($cues|?{$_.T-ge$times[$i]-and$_.T-lt$next});$n=Clean $a;$sample=if($n.Length-gt220){$n.Substring(0,220)+'…'}else{$n};$ttl=if($i-and(Topic $times[$i-1]).T-eq$tp.T){"$($tp.T)（續）"}else{$tp.T};$base="`n### Slide $($i+1) — $ttl ([Video]($url&t=$($times[$i])s))`n`n![Slide $($i+1) — $ttl](slides/$fn)`n`n$($tp.X) 本段重點：$sample`n";@($std,$clean,$detail)|%{[void]$_.AppendLine($base)};[void]$std.AppendLine("`n<details>`n<summary><strong>Cleaned narration</strong></summary>`n`n> $n`n`n</details>`n");[void]$detail.AppendLine("`n<details>`n<summary><strong>All subtitles</strong></summary>`n");$ls=New-Object Collections.Generic.List[string];$line='';foreach($c in $a){$q=if($line){$line+' '+$c.X}else{$c.X};if($line-and$q.Length-gt64){$ls.Add($line);$line=$c.X}else{$line=$q}};if($line){$ls.Add($line)};if($ls.Count-gt1-and$ls[-1].Length-lt32){$z=$ls[-1];$ls.RemoveAt($ls.Count-1);$ls[-1]+=' '+$z};$ls|%{[void]$detail.AppendLine('> '+$_)};[void]$detail.AppendLine("`n</details>`n")};$tail="`n## 核心結論`n`n- 單次自我修正不等於持久自我成長；關鍵是能力是否被寫回模型或學習系統。`n- Proxy reward、AI evaluator 與 entropy 可降低人類標註需求，但都可能偏離真實目標。`n- 無人自訓能帶來有限進步，常受初始模型能力、訊號品質與飽和限制。`n- AI 設計訓練演算法已顯示潛力，但尚未證明能遞迴產生超越自身的系統。`n";@($std,$clean,$detail)|%{[void]$_.AppendLine($tail)};[IO.File]::WriteAllText("$dir\$title - Slide Notes.md",$std,$u);[IO.File]::WriteAllText("$dir\$title - Clean Slide Notes.md",$clean,$u);[IO.File]::WriteAllText("$dir\$title - Detail Slide Notes.md",$detail,$u);"Generated $($times.Count) slides, $($cues.Count) cues"
