$ErrorActionPreference='Stop';$dir=Join-Path (Get-Location).ProviderPath 'lihongyi_ml\讓 AI 自動找到更好的 Decoding 方法：從 Workflow 到 Reasoning Model';$src="$dir\source";$out="$dir\slides";New-Item -ItemType Directory -Force $out|Out-Null;$title='讓 AI 自動找到更好的 Decoding 方法：從 Workflow 到 Reasoning Model';$url='https://www.youtube.com/watch?v=m3i2mk5hs8U'
$times=@(0,15,60,87,129,159,162,249,336,378,441,474,681,717,882,1077,1188,1293,1335,1422,1458,1557,1584,1665,1716,1779,1854,1998,2058,2142,2196,2238,2256,2316,2415,2424,2442,2742,2862,2997,3048,3129,3237,3261,3282,3381,3405,3459,3699,3708,3798,3885,3912,3993,4086,4095,4173,4200,4305,4368,4494,4701,4791,4944,4980,5025,5052,5166,5253)
$topics=@(
@{End=441;Sec='一、Self-Correction 問題';Title='模型能否在無人介入下自我修正？';Exp='語言模型能依人類回饋改錯，但更難的問題是：輸出後能否自己發現錯誤並修正。課程把方法分為改 decoding、加入 workflow，以及直接訓練 reasoning behavior。'},
@{End=882;Sec='二、Contrastive Decoding';Title='用「故意答錯」的模型訊號做對比';Exp='Contrastive decoding 比較正常條件與刻意破壞條件下的 logits／representation，減去較可能造成錯誤的成分，再進行 sampling。它把 error detection 與 correction 合併，而且不必收集額外標註。'},
@{End=1293;Sec='三、DoLa 與 Logit Lens';Title='Decoding by Contrasting Layers';Exp='Logit lens 將中間層 representation 投影到詞彙空間，觀察知識如何隨深度形成。DoLa 將成熟層與較早、較不可靠層的預測做對比，強化後期形成的 factual signal；Hugging Face 已提供推論選項。'},
@{End=1716;Sec='四、用指令或 Context 製造負例';Title='Instruction 與 Context-Aware Decoding';Exp='ICD 用「你會給錯答案」等降智指令產生負 logits；CAD 比較有無檢索 context 的輸出，抑制模型只靠內部先驗、忽略證據的傾向。負例如何製造直接決定方法效果。'},
@{End=2142;Sec='五、多模態 Contrastive Decoding';Title='Visual／Audio-Aware Decoding';Exp='多模態方法比較正常影像或音訊與移除、遮蔽、靜音後的輸出，減去不依賴感知輸入的語言先驗，促使答案真正 grounded 在視覺或聲音證據上。'},
@{End=2442;Sec='六、Decoding 係數與負提示搜尋';Title='負成分減多少、用哪個負提示？';Exp='對比係數過小無效，過大也會破壞輸出。實驗顯示合適係數能顯著提升正確率，且通用 Output Error 不一定是最佳降智提示；可搜尋更適合任務的負條件。'},
@{End=2862;Sec='七、Generation–Verification Workflow';Title='自動插入反思與驗證';Exp='Workflow 在第一次答案後自動插入通用反思指令，再讓模型檢查和修正，无需人類逐題介入。它提供額外 test-time compute，但會讓正確答案也被迫重想並可能改壞。'},
@{End=3282;Sec='八、自我反思的實證限制';Title='強模型反覆反思通常只小幅改善';Exp='RefineBench 等大規模研究發現，強模型單靠「再想想」的多輪 self-refinement 增益有限；若加入外部 critique、工具結果或正確性訊號，改善才更明顯。'},
@{End=3699;Sec='九、反思提示如何改變信心';Title='肯定使模型固執，質疑提高修改率';Exp='即使提示由程式自動插入，肯定原答案會提高 confidence、降低改答案機率；質疑則降低信心、提高 critic score。所謂自我反思可能部分只是被提示誘導，而非真正偵測錯誤。'},
@{End=4086;Sec='十、從 Workflow 到 Reasoning';Title='讓模型自己決定何時繼續思考';Exp='Workflow 固定插入額外指令，不論答案對錯都增加 token。Reasoning model 期待把行為內化：需要時自行修正，不需要時停止，降低固定流程的浪費並提高適應性。'},
@{End=4494;Sec='十一、用 RL 訓練 Reasoning';Title='Reinforcement Learning with Verifiable Rewards';Exp='數學和程式任務可自動驗證答案，適合以最終正確性給 reward。RL 不指定中間 token，只獎勵最後結果，模型可能自行發展長推理、檢查和回溯策略；但也可能利用 verifier 漏洞。'},
@{End=4944;Sec='十二、Reasoning 如何改善泛化';Title='Parity 範例：學演算法而非死背';Exp='固定長度 parity 可死背所有輸入；若要求模型產生逐步推理，模型可能學到可延伸到更長序列的計數或狀態更新演算法。Reasoning 的價值在建立可組合程序，而非只增加輸出字數。'},
@{End=5263;Sec='十三、Training-Free Reasoning Decoding';Title='更好的 Sampling 能否逼出既有能力？';Exp='若未經 RL 的模型偶爾已能 sample 到正確推理，能力可能本來就在分布中。新的 training-free sampling／search 方法可在不更新參數下提高找到好 reasoning path 的機率，有時接近 RL 模型。'})
$cues=New-Object Collections.Generic.List[object];$st=$null;$buf=New-Object Collections.Generic.List[string]
function Flush{if($null-ne$script:st-and$script:buf.Count){$x=[Net.WebUtility]::HtmlDecode((($script:buf-join' ')-replace'<[^>]+>',''));$x=($x-replace'\s+',' ').Trim();if($x){$p=$script:st.Split(':');$cues.Add([pscustomobject]@{T=[double]$p[0]*3600+[double]$p[1]*60+[double]$p[2];S=$script:st.Substring(0,8);X=$x})}};$script:buf.Clear()}
foreach($l in Get-Content -Encoding UTF8 "$src\video.zh-TW.vtt"){if($l-match'^(\d\d:\d\d:\d\d\.\d+) -->'){Flush;$st=$matches[1]}elseif(-not$l.Trim()){Flush;$st=$null}elseif($null-ne$st-and$l-notmatch'^(WEBVTT|Kind:|Language:)'){$buf.Add($l.Trim())}};Flush
$u=[Text.UTF8Encoding]::new($false);[IO.File]::WriteAllLines("$src\transcript.txt",@($cues|%{"[$($_.S)] $($_.X)"}),$u)
function Stamp([int]$s,[string]$z='-'){('{0:D2}{3}{1:D2}{3}{2:D2}'-f[int]($s/3600),[int](($s/60)%60),[int]($s%60),$z)}
function Topic([int]$t){foreach($q in $topics){if($t-lt$q.End){return $q}};return $topics[-1]}
function CleanNarr([object[]]$a){$xs=New-Object Collections.Generic.List[string];foreach($c in $a){$v=$c.X.Trim();if($v-match'^(好|那|然後|對|OK|好那|那接下來呢|那這邊呢|大家好|有沒有|對不對)$'){continue};$v=$v-replace'^(好|那|然後|所以說|也就是說|接下來|這邊|我們可以看到)[， ]*','';$v=$v-replace'(其實|基本上|簡單來說|換句話說)[， ]*','';if($v-and($xs.Count-eq0-or$xs[-1]-ne$v)){$xs.Add($v)}};$r=(($xs-join' ')-replace'\s+',' ').Trim();$raw=((@($a).X-join' ')-replace'\s+',' ').Trim();if($r-ceq$raw-and$r){$r='重點是，'+$r};return $r}
$csv=New-Object Collections.Generic.List[string];$csv.Add('slide,timestamp_seconds,timestamp,file');for($i=0;$i-lt$times.Count;$i++){$fn=('{0:D3}_{1}.jpg'-f($i+1),(Stamp $times[$i]));Copy-Item -Force "$dir\slides_raw\scene_$('{0:D4}'-f($i+1)).jpg" "$out\$fn";$csv.Add(('"{0}","{1}","{2}","{3}"'-f($i+1),$times[$i],(Stamp $times[$i] ':'),$fn))};[IO.File]::WriteAllLines("$out\index.csv",$csv,$u)
$head="# $title`n`n- 講者：李宏毅`n- 影片：[YouTube]($url)`n- 長度：1:27:42`n- 字幕：原始繁體中文字幕`n`n本講探討語言模型能否自我修正，從 contrastive decoding、DoLa、多模態對比、generation–verification workflow，一路談到以 RL 或 training-free sampling 形成 reasoning behavior。時間資料保存在 ``source/transcript.txt`` 與 ``slides/index.csv``。`n";$std=New-Object Text.StringBuilder;$clean=New-Object Text.StringBuilder;$detail=New-Object Text.StringBuilder;@($std,$clean,$detail)|%{[void]$_.AppendLine($head)};$last=''
for($i=0;$i-lt$times.Count;$i++){$tp=Topic $times[$i];if($tp.Sec-ne$last){@($std,$clean,$detail)|%{[void]$_.AppendLine("`n## $($tp.Sec)")};$last=$tp.Sec};$fn=('{0:D3}_{1}.jpg'-f($i+1),(Stamp $times[$i]));$next=if($i+1-lt$times.Count){$times[$i+1]}else{5263};$a=@($cues|?{$_.T-ge$times[$i]-and$_.T-lt$next});$n=CleanNarr $a;$sample=if($n.Length-gt240){$n.Substring(0,240)+'…'}else{$n};$prev=if($i){(Topic $times[$i-1]).Title}else{''};$ttl=if($tp.Title-ne$prev){$tp.Title}else{"$($tp.Title)（續）"};$base="`n### Slide $($i+1) — $ttl ([Video]($url&t=$($times[$i])s))`n`n![Slide $($i+1) — $ttl](slides/$fn)`n`n$($tp.Exp) 本段重點：$sample`n";@($std,$clean,$detail)|%{[void]$_.AppendLine($base)};[void]$std.AppendLine("`n<details>`n<summary><strong>Cleaned narration</strong></summary>`n`n> $n`n`n</details>`n");[void]$detail.AppendLine("`n<details>`n<summary><strong>All subtitles</strong></summary>`n");$ls=New-Object Collections.Generic.List[string];$line='';foreach($c in $a){$q=if($line){$line+' '+$c.X}else{$c.X};if($line-and$q.Length-gt64){$ls.Add($line);$line=$c.X}else{$line=$q}};if($line){$ls.Add($line)};if($ls.Count-gt1-and$ls[-1].Length-lt32){$z=$ls[-1];$ls.RemoveAt($ls.Count-1);$ls[-1]+=' '+$z};$ls|%{[void]$detail.AppendLine('> '+$_)};[void]$detail.AppendLine("`n</details>`n")}
$tail="`n## 核心結論`n`n- Contrastive decoding 以正常與故意破壞條件的差異抑制錯誤成分。`n- 固定反思 workflow 可增加 test-time compute，但不保證真正偵測錯誤，還可能改壞正確答案。`n- 外部 critique、工具與 verifier 通常比空泛的「再想想」更可靠。`n- Reasoning model 將何時思考與修正內化到模型行為，可用 verifiable reward 訓練。`n- Training-free search 顯示部分 reasoning 能力可能已存在於原模型分布，只是普通 sampling 不容易找到。`n";@($std,$clean,$detail)|%{[void]$_.AppendLine($tail)};[IO.File]::WriteAllText("$dir\$title - Slide Notes.md",$std,$u);[IO.File]::WriteAllText("$dir\$title - Clean Slide Notes.md",$clean,$u);[IO.File]::WriteAllText("$dir\$title - Detail Slide Notes.md",$detail,$u);"Generated $($times.Count) slides, $($cues.Count) cues"
